namespace BusinessLogic
{
    public enum BlEvents
    {
        SystemScanStarted,
        SystemScanStopped,
        SystemScanAbortedError,
        SystemScanCompleted,
        CveCheckStarted,
        CveCheckCompleted,
        CheckingInternetStatus,
        CheckingInternetStatusCompleted,
        CheckingSecurityProducts,
        CheckingSecurityProductsCompleted,
        CheckingWindowsVersion,
        CheckingWindowsVersionCompleted,
        CheckingApplicationVersions,
        CheckingApplicationVersionsCompleted,
        CheckingElevatedUser,
        CheckingElevatedUserCompleted,
        CheckingWindowsScriptingHost,
        CheckingWindowsScriptingHostCompleted,
        CheckingRdpEnabled,
        CheckingRdpEnabledCompleted,
        CheckingSecureBootEnabled,
        CheckingSecureBootEnabledCompleted,
        CheckingFirewall,
        CheckingFirewallCompleted,
        CheckingRegularUpdates,
        CheckingRegularUpdatesCompleted,
        CheckingBitLocker,
        CheckingBitLockerCompleted
    }
}
